global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'user_service'
    metrics_path: '/user/actuator/prometheus'
    static_configs:
      - targets: [ 'user-service:8080' ]
        labels:
          application: 'User Service Application'
  - job_name: 'theatre_service'
    metrics_path: '/theatre/actuator/prometheus'
    static_configs:
      - targets: [ 'theatre-service:8080' ]
        labels:
          application: 'Theatre Service Application'
  - job_name: 'movie_service'
    metrics_path: '/movie/actuator/prometheus'
    static_configs:
      - targets: [ 'movie-service:8080' ]
        labels:
          application: 'Movie Service Application'
